# Buildpacks to include in builder
[[buildpacks]]
id = "spring-boot/test-info"
version = "0.0.2"
uri = "../buildpacks/test-info"

# Order used for detection
[[order]]
[[order.group]]
id = "spring-boot/test-info"
version = "0.0.2"

# Stack that will be used by the builder
[stack]
id = "io.paketo.stacks.tiny"
build-image = "projects.registry.vmware.com/springboot/build:tiny-cnb"
run-image = "projects.registry.vmware.com/springboot/run:tiny-cnb"

# Lifecycle executable version that will be used by the builder
[lifecycle]
version = "0.15.3"